# .github/workflows/deploy.yml
name: Trigger Netlify Deploy Hook

on:
  push:
    branches: [main]

jobs:
  trigger-vercel:
    runs-on: ubuntu-latest
    steps:
      - name: Curl to Netlify Deploy Hook
        run: curl -X POST ${{ secrets.NETLIFYL_DEPLOY_HOOK }}
